-- Proveedor (docs/DOMAIN_MODEL.md, seccion 2.10; RF-012). Ciclo minimo
-- necesario para soportar ordenes de compra: sin borrado fisico (ON DELETE
-- RESTRICT desde purchase_order), solo baja logica (active).
CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    tax_id VARCHAR(50) NOT NULL UNIQUE,
    contact_name VARCHAR(150),
    phone VARCHAR(30),
    email VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
