-- Orden de compra (docs/DOMAIN_MODEL.md, seccion 2.11; RF-012, RF-013).
-- "order_number" lo genera la aplicacion (no es un campo del request de
-- creacion, ver docs/openapi.yaml PurchaseOrderCreateRequest) - ver
-- PurchaseOrderService para el esquema de generacion.
--
-- Sin created_by/updated_by de Auditable: el encabezado no se edita despues
-- de creado (docs/DOMAIN_MODEL.md, 2.11); el responsable de creacion ya
-- queda registrado en created_by_user_id, y el "status" avanza mediante
-- transiciones explicitas, no ediciones genericas.
CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(30) NOT NULL UNIQUE,
    supplier_id BIGINT NOT NULL REFERENCES supplier(id) ON DELETE RESTRICT,
    branch_id BIGINT NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL,
    payment_term VARCHAR(100),
    order_date TIMESTAMPTZ NOT NULL,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_purchase_order_status CHECK (status IN ('CREATED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'))
);

CREATE INDEX idx_purchase_order_branch ON purchase_order (branch_id);
CREATE INDEX idx_purchase_order_supplier ON purchase_order (supplier_id);
