-- Venta (docs/DOMAIN_MODEL.md, seccion 2.15; RF-017 a RF-021). Se crea
-- directamente en CONFIRMED (sin estado borrador). status solo admite
-- 'CONFIRMED' en esta fase: VOIDED sigue como decision de aprobacion
-- pendiente (seccion "Decisiones que requieren aprobacion", punto 9) - el
-- CHECK se deja abierto para no tener que migrar de nuevo si se aprueba
-- despues, pero la aplicacion (SaleStatus) no lo produce todavia.
--
-- client_reference_id resuelve la decision pendiente #5 de
-- docs/BUSINESS_RULES.md: clave de idempotencia para el registro de venta
-- (categoria 2 - creacion repetible, docs/CRITICAL_FLOWS.md flujo A).
CREATE TABLE sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number VARCHAR(30) NOT NULL UNIQUE,
    branch_id BIGINT NOT NULL REFERENCES branch(id) ON DELETE RESTRICT,
    sold_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    price_list_id BIGINT NOT NULL REFERENCES price_list(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL,
    sale_date TIMESTAMPTZ NOT NULL,
    subtotal NUMERIC(19,4) NOT NULL,
    discount_total NUMERIC(19,4) NOT NULL,
    total NUMERIC(19,4) NOT NULL,
    client_reference_id VARCHAR(150) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_sale_status CHECK (status IN ('CONFIRMED', 'VOIDED')),
    CONSTRAINT chk_sale_totals_non_negative CHECK (subtotal >= 0 AND discount_total >= 0 AND total >= 0)
);

CREATE INDEX idx_sale_branch ON sale (branch_id);
CREATE INDEX idx_sale_date ON sale (sale_date DESC);
