-- Alertas de stock minimo (docs/DOMAIN_MODEL.md, seccion 2.9; BR-010; UC-16;
-- RF-010/RF-036 - funcionalidad adicional elegida).
--
-- El indice unico parcial es la garantia real contra alertas activas
-- duplicadas (BR-010): en vez de una comprobacion de aplicacion propensa a
-- condicion de carrera, se deja que PostgreSQL la rechace de raiz. Una
-- alerta resuelta no se elimina (historial de reabastecimiento) y una nueva
-- caida de stock despues de resolver crea una fila nueva, nunca reabre la
-- anterior.
CREATE TABLE stock_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL REFERENCES inventory(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL,
    triggered_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_stock_alert_status CHECK (status IN ('ACTIVE', 'RESOLVED'))
);

CREATE UNIQUE INDEX uq_stock_alert_active_per_inventory ON stock_alert (inventory_id) WHERE status = 'ACTIVE';
