-- Modelo minimo de sucursal (docs/DOMAIN_MODEL.md, seccion 2.1), suficiente
-- para users.branch_id y para las pruebas de autorizacion por sucursal
-- (BR-018). El modulo funcional completo de sucursales (mas columnas, CRUD
-- vía API) es alcance de una fase posterior.
CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
