-- Modelo minimo de usuario (docs/DOMAIN_MODEL.md, seccion 2.3; RF-037 a
-- RF-039). Nombre de tabla en plural ("users", no "user"): "user" es palabra
-- reservada en PostgreSQL.
--
-- El CHECK es la regla de negocio "solo ADMIN puede carecer de sucursal"
-- aplicada en la base de datos, no solo en el codigo de aplicacion (docs
-- pedian explicitamente aprovechar constraints de PostgreSQL en vez de
-- trasladar toda la integridad al backend).
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_code VARCHAR(20) NOT NULL REFERENCES role(code),
    branch_id BIGINT REFERENCES branch(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT chk_users_admin_no_branch CHECK ((role_code = 'ADMIN') OR (branch_id IS NOT NULL))
);
