-- Producto (docs/DOMAIN_MODEL.md, seccion 2.5; RF-005). Deliberadamente sin
-- ninguna columna de stock/cantidad - eso es Inventory, un modulo aparte
-- todavia no implementado (ver condicion de parada de esta fase).
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    base_unit_of_measure_id BIGINT NOT NULL REFERENCES unit_of_measure(id) ON DELETE RESTRICT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);
