-- Relacion producto<->unidad de medida con factor de conversion hacia la
-- unidad base (docs/DOMAIN_MODEL.md, seccion 2.6; BR-011).
--
-- uq_product_unit: un producto no puede tener la misma unidad asociada dos veces.
-- uq_product_unit_single_base: exactamente una unidad base por producto -
-- se aplica en base de datos (indice unico parcial), no solo en el codigo
-- de aplicacion, para que la invariante no dependa de que nadie la rompa
-- por error.
-- chk_conversion_factor_positive: la conversion nunca puede ser cero/negativa
-- (BR-011, "conversiones deben ser deterministas y validadas").
CREATE TABLE product_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    unit_of_measure_id BIGINT NOT NULL REFERENCES unit_of_measure(id) ON DELETE RESTRICT,
    conversion_factor_to_base NUMERIC(19,6) NOT NULL,
    is_base_unit BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT uq_product_unit UNIQUE (product_id, unit_of_measure_id),
    CONSTRAINT chk_conversion_factor_positive CHECK (conversion_factor_to_base > 0)
);

CREATE UNIQUE INDEX uq_product_unit_single_base ON product_unit (product_id) WHERE is_base_unit;
